pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ">=20.0.0"
    displayName: "Install Node.js>20"

  - script: |
      npm ci
      npx playwright install --with-deps
    displayName: "Install dependencies"

  - script: |
      npm install -g allure-commandline  
    displayName: "Install Allure"

  - script: |
      npx playwright test --reporter=html,junit
    workingDirectory:  $(build.sourcesdirectory)/tests
    displayName: "Run Playwright tests"
    env:
      CI: 'true'
      ADO_TOKEN: $(ADO_TOKEN)

  - script: |
      allure generate --single-file allure-results
    displayName: 'Generate allure report'
    condition: always()

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: "test-results"
      ArtifactName: "playwright-report-user3"
      publishLocation: "Container"

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFiles: "**/results.xml"
      testRunTitle: "Playwright Junit Test Results"
      mergeTestResults: true

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: "./allure-report"  # Ensure this path matches where the report is generated
      ArtifactName: "allure-report"
      publishLocation: "Container"

  - task: PublishAllureReport@1
    condition: always()
    displayName: Publish Allure Report
    inputs:
      allureVersion: 2.27.0
      testResultsDir: allure-results
