trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: pageUrl
    displayName: Page to test
    type: string
    default: https://www.google.com
  - name: debugPause
    displayName: Miliseconds to pause
    type: number
    default: 2000
  - name: environment
    displayName: Environment
    type: string
    default: 'dev'
    values:
      - dev
      - staging
      - production

variables:
  pageURL: ${{ parameters.pageUrl }}
  debugPause: ${{ parameters.debugPause }}

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '>=20.0.0'
    displayName: 'Install Node.js>20'

  - script: |
      npm install
      npx playwright install
    displayName: 'Install dependencies'

  - script: |
      npx playwright test --config=playwright.a11y.config.ts tests/Accessibility/pageAccessibility.spec.ts --project=desktop-chromium
    displayName: 'Run Playwright tests'
    env:
      PAGE_URL: $(pageUrl)
      DEBUG_PAUSE: $(debugPause)
      PAT_TOKEN_PACKAGE: $(patTokenPackage)