name: Run a11y tool
on:
  workflow_dispatch:
    inputs:
      PAGE_URL:
        description: "URL to test"
        required: true
      DEBUG_PAUSE:
        description: "Miliseconds to pause"
        required: true
jobs:
  test:
    timeout-minutes: 60
    name: Test Accessibility
    runs-on: ubuntu-latest
    env:
      PAGE_URL: ${{ inputs.PAGE_URL }}
      DEBUG_PAUSE: ${{ inputs.DEBUG_PAUSE }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm config set @microsoft:registry=https://npm.pkg.github.com
          npm set //npm.pkg.github.com/:_authToken ${{secrets.PAT_TOKEN_PACKAGE}}
          npm ci

      - run: npx playwright install --with-deps

      - name: Run accessibility tests
        run: PLAYWRIGHT_HTML_REPORT=chromium npx playwright test tests/Accessibility/pageAccessibility --project=chromium --workers=1

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Axe accessibility report
          path: chromium/
          retention-days: 5

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Results
          path: test-results/
          retention-days: 5

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Annotations
          path: test-annotations/
          retention-days: 5
