name: Run a11y tool
on:
  workflow_dispatch:
    inputs:
      PAGE_URL:
        description: "URL to test"
        required: true
      DEBUG_PAUSE:
        description: "Miliseconds to pause"
        required: true
jobs:
  test:
    timeout-minutes: 60
    name: Test Accessibility
    runs-on: ubuntu-latest
    env:
      PAGE_URL: ${{ inputs.PAGE_URL }}
      DEBUG_PAUSE: ${{ inputs.DEBUG_PAUSE }}
      PAT_TOKEN_PACKAGE: ${{secrets.PAT_TOKEN_PACKAGE}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm config set @microsoft:registry=https://npm.pkg.github.com
          npm set //npm.pkg.github.com/:_authToken ${{secrets.PAT_TOKEN_PACKAGE}}
          npm ci

      - run: npx playwright install --with-deps

      - name: Run accessibility tests
        run: npx playwright test tests/Accessibility/pageAccessibility --project=desktop-chromium --workers=1 --reporter=html,junit,./utils/reporter/StepReporter.ts,./utils/accessibility/AccessibilityReporter

      - name: Upload reporter as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: steps-report
          path: steps-report/
          retention-days: 5
