name: Run a11y tool
on:
  workflow_dispatch:
    inputs:
      PAGE_URL:
        description: "URL to test"
        required: true
jobs:
  test:
    timeout-minutes: 60
    name: Test Accessibility
    runs-on: ubuntu-latest
    env:
      PAGE_URL: ${{ inputs.PAGE_URL }}
      ADO_ORGANIZATION: ${{ vars.ADO_ORGANIZATION }}
      ADO_PROJECT: ${{ vars.ADO_PROJECT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm ci

      - run: npx playwright install --with-deps

      - name: Run accessibility tests
        run: PLAYWRIGHT_HTML_REPORT=report npx playwright test --config=playwright.a11y.config.ts tests/Accessibility/pageAccessibility.spec.ts --project=desktop-chromium

      - name: Upload reporter as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: a11y-report
          path: steps-report/
          retention-days: 5
